<?php

namespace Proxies\__CG__\Materiaweb\MateriaBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ArticulosPreciosCostos extends \Materiaweb\MateriaBundle\Entity\ArticulosPreciosCostos implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'ArtPrecCostIdTabla', 'ArtPrecCostIdCompany', 'ArtPrecCostCodart', 'ArtPrecCostNroOrden', 'ArtPrecCostDetalle', 'ArtPrecCostValor', 'ArtPrecCostMoneda', 'ArtPrecCostIdentificador');
        }

        return array('__isInitialized__', 'ArtPrecCostIdTabla', 'ArtPrecCostIdCompany', 'ArtPrecCostCodart', 'ArtPrecCostNroOrden', 'ArtPrecCostDetalle', 'ArtPrecCostValor', 'ArtPrecCostMoneda', 'ArtPrecCostIdentificador');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (ArticulosPreciosCostos $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getArtPrecCostIdTabla()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArtPrecCostIdTabla', array());

        return parent::getArtPrecCostIdTabla();
    }

    /**
     * {@inheritDoc}
     */
    public function setArtPrecCostIdCompany($artPrecCostIdCompany)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArtPrecCostIdCompany', array($artPrecCostIdCompany));

        return parent::setArtPrecCostIdCompany($artPrecCostIdCompany);
    }

    /**
     * {@inheritDoc}
     */
    public function getArtPrecCostIdCompany()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArtPrecCostIdCompany', array());

        return parent::getArtPrecCostIdCompany();
    }

    /**
     * {@inheritDoc}
     */
    public function setArtPrecCostCodart($artPrecCostCodart)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArtPrecCostCodart', array($artPrecCostCodart));

        return parent::setArtPrecCostCodart($artPrecCostCodart);
    }

    /**
     * {@inheritDoc}
     */
    public function getArtPrecCostCodart()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArtPrecCostCodart', array());

        return parent::getArtPrecCostCodart();
    }

    /**
     * {@inheritDoc}
     */
    public function setArtPrecCostNroOrden($artPrecCostNroOrden)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArtPrecCostNroOrden', array($artPrecCostNroOrden));

        return parent::setArtPrecCostNroOrden($artPrecCostNroOrden);
    }

    /**
     * {@inheritDoc}
     */
    public function getArtPrecCostNroOrden()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArtPrecCostNroOrden', array());

        return parent::getArtPrecCostNroOrden();
    }

    /**
     * {@inheritDoc}
     */
    public function setArtPrecCostDetalle($artPrecCostDetalle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArtPrecCostDetalle', array($artPrecCostDetalle));

        return parent::setArtPrecCostDetalle($artPrecCostDetalle);
    }

    /**
     * {@inheritDoc}
     */
    public function getArtPrecCostDetalle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArtPrecCostDetalle', array());

        return parent::getArtPrecCostDetalle();
    }

    /**
     * {@inheritDoc}
     */
    public function setArtPrecCostValor($artPrecCostValor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArtPrecCostValor', array($artPrecCostValor));

        return parent::setArtPrecCostValor($artPrecCostValor);
    }

    /**
     * {@inheritDoc}
     */
    public function getArtPrecCostValor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArtPrecCostValor', array());

        return parent::getArtPrecCostValor();
    }

    /**
     * {@inheritDoc}
     */
    public function setArtPrecCostMoneda($artPrecCostMoneda)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArtPrecCostMoneda', array($artPrecCostMoneda));

        return parent::setArtPrecCostMoneda($artPrecCostMoneda);
    }

    /**
     * {@inheritDoc}
     */
    public function getArtPrecCostMoneda()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArtPrecCostMoneda', array());

        return parent::getArtPrecCostMoneda();
    }

    /**
     * {@inheritDoc}
     */
    public function setArtPrecCostIdentificador($artPrecCostIdentificador)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArtPrecCostIdentificador', array($artPrecCostIdentificador));

        return parent::setArtPrecCostIdentificador($artPrecCostIdentificador);
    }

    /**
     * {@inheritDoc}
     */
    public function getArtPrecCostIdentificador()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArtPrecCostIdentificador', array());

        return parent::getArtPrecCostIdentificador();
    }

}
