<?php

namespace Proxies\__CG__\Materiaweb\MateriaBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Articulos extends \Materiaweb\MateriaBundle\Entity\Articulos implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'articuloId', 'articuloIdCompany', 'articuloCodart', 'articuloCodartAlternativo', 'articuloCategoria', 'articuloCodigoFamilia', 'articuloNombre', 'articuloNombreReduc', 'articuloUnidad', 'articuloCantxBulto', 'articuloBultoxPallet', 'articuloKgsUnidad', 'articuloCodAlicuota', 'articuloPuntoContVenta', 'articuloPuntoContCompra', 'articuloExistMinima', 'articuloExistMaxima', 'articuloCodigoBarra', 'articuloPresentacion');
        }

        return array('__isInitialized__', 'articuloId', 'articuloIdCompany', 'articuloCodart', 'articuloCodartAlternativo', 'articuloCategoria', 'articuloCodigoFamilia', 'articuloNombre', 'articuloNombreReduc', 'articuloUnidad', 'articuloCantxBulto', 'articuloBultoxPallet', 'articuloKgsUnidad', 'articuloCodAlicuota', 'articuloPuntoContVenta', 'articuloPuntoContCompra', 'articuloExistMinima', 'articuloExistMaxima', 'articuloCodigoBarra', 'articuloPresentacion');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Articulos $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getArticuloCodart()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getArticuloCodart();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArticuloCodart', array());

        return parent::getArticuloCodart();
    }

    /**
     * {@inheritDoc}
     */
    public function setArticuloIdCompany($articuloIdCompany)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArticuloIdCompany', array($articuloIdCompany));

        return parent::setArticuloIdCompany($articuloIdCompany);
    }

    /**
     * {@inheritDoc}
     */
    public function getArticuloIdCompany()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArticuloIdCompany', array());

        return parent::getArticuloIdCompany();
    }

    /**
     * {@inheritDoc}
     */
    public function setArticuloCodartAlternativo($articuloCodartAlternativo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArticuloCodartAlternativo', array($articuloCodartAlternativo));

        return parent::setArticuloCodartAlternativo($articuloCodartAlternativo);
    }

    /**
     * {@inheritDoc}
     */
    public function getArticuloCodartAlternativo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArticuloCodartAlternativo', array());

        return parent::getArticuloCodartAlternativo();
    }

    /**
     * {@inheritDoc}
     */
    public function setArticuloCodigoFamilia($articuloCodigoFamilia)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArticuloCodigoFamilia', array($articuloCodigoFamilia));

        return parent::setArticuloCodigoFamilia($articuloCodigoFamilia);
    }

    /**
     * {@inheritDoc}
     */
    public function getArticuloCodigoFamilia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArticuloCodigoFamilia', array());

        return parent::getArticuloCodigoFamilia();
    }

    /**
     * {@inheritDoc}
     */
    public function setArticuloCategoria($articuloCategoria)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArticuloCategoria', array($articuloCategoria));

        return parent::setArticuloCategoria($articuloCategoria);
    }

    /**
     * {@inheritDoc}
     */
    public function getArticuloCategoria()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArticuloCategoria', array());

        return parent::getArticuloCategoria();
    }

    /**
     * {@inheritDoc}
     */
    public function setArticuloNombre($articuloNombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArticuloNombre', array($articuloNombre));

        return parent::setArticuloNombre($articuloNombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getArticuloNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArticuloNombre', array());

        return parent::getArticuloNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setArticuloNombreReduc($articuloNombreReduc)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArticuloNombreReduc', array($articuloNombreReduc));

        return parent::setArticuloNombreReduc($articuloNombreReduc);
    }

    /**
     * {@inheritDoc}
     */
    public function getArticuloNombreReduc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArticuloNombreReduc', array());

        return parent::getArticuloNombreReduc();
    }

    /**
     * {@inheritDoc}
     */
    public function setArticuloUnidad($articuloUnidad)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArticuloUnidad', array($articuloUnidad));

        return parent::setArticuloUnidad($articuloUnidad);
    }

    /**
     * {@inheritDoc}
     */
    public function getArticuloUnidad()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArticuloUnidad', array());

        return parent::getArticuloUnidad();
    }

    /**
     * {@inheritDoc}
     */
    public function setArticuloCantxBulto($articuloCantxBulto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArticuloCantxBulto', array($articuloCantxBulto));

        return parent::setArticuloCantxBulto($articuloCantxBulto);
    }

    /**
     * {@inheritDoc}
     */
    public function getArticuloCantxBulto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArticuloCantxBulto', array());

        return parent::getArticuloCantxBulto();
    }

    /**
     * {@inheritDoc}
     */
    public function setArticuloBultoxPallet($articuloBultoxPallet)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArticuloBultoxPallet', array($articuloBultoxPallet));

        return parent::setArticuloBultoxPallet($articuloBultoxPallet);
    }

    /**
     * {@inheritDoc}
     */
    public function getArticuloBultoxPallet()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArticuloBultoxPallet', array());

        return parent::getArticuloBultoxPallet();
    }

    /**
     * {@inheritDoc}
     */
    public function setArticuloKgsUnidad($articuloKgsUnidad)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArticuloKgsUnidad', array($articuloKgsUnidad));

        return parent::setArticuloKgsUnidad($articuloKgsUnidad);
    }

    /**
     * {@inheritDoc}
     */
    public function getArticuloKgsUnidad()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArticuloKgsUnidad', array());

        return parent::getArticuloKgsUnidad();
    }

    /**
     * {@inheritDoc}
     */
    public function setArticuloCodAlicuota($articuloCodAlicuota)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArticuloCodAlicuota', array($articuloCodAlicuota));

        return parent::setArticuloCodAlicuota($articuloCodAlicuota);
    }

    /**
     * {@inheritDoc}
     */
    public function getArticuloCodAlicuota()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArticuloCodAlicuota', array());

        return parent::getArticuloCodAlicuota();
    }

    /**
     * {@inheritDoc}
     */
    public function setArticuloPuntoContVenta($articuloPuntoContVenta)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArticuloPuntoContVenta', array($articuloPuntoContVenta));

        return parent::setArticuloPuntoContVenta($articuloPuntoContVenta);
    }

    /**
     * {@inheritDoc}
     */
    public function getArticuloPuntoContVenta()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArticuloPuntoContVenta', array());

        return parent::getArticuloPuntoContVenta();
    }

    /**
     * {@inheritDoc}
     */
    public function setArticuloPuntoContCompra($articuloPuntoContCompra)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArticuloPuntoContCompra', array($articuloPuntoContCompra));

        return parent::setArticuloPuntoContCompra($articuloPuntoContCompra);
    }

    /**
     * {@inheritDoc}
     */
    public function getArticuloPuntoContCompra()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArticuloPuntoContCompra', array());

        return parent::getArticuloPuntoContCompra();
    }

    /**
     * {@inheritDoc}
     */
    public function setArticuloExistMinima($articuloExistMinima)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArticuloExistMinima', array($articuloExistMinima));

        return parent::setArticuloExistMinima($articuloExistMinima);
    }

    /**
     * {@inheritDoc}
     */
    public function getArticuloExistMinima()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArticuloExistMinima', array());

        return parent::getArticuloExistMinima();
    }

    /**
     * {@inheritDoc}
     */
    public function setArticuloExistMaxima($articuloExistMaxima)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArticuloExistMaxima', array($articuloExistMaxima));

        return parent::setArticuloExistMaxima($articuloExistMaxima);
    }

    /**
     * {@inheritDoc}
     */
    public function getArticuloExistMaxima()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArticuloExistMaxima', array());

        return parent::getArticuloExistMaxima();
    }

    /**
     * {@inheritDoc}
     */
    public function setArticuloCodigoBarra($articuloCodigoBarra)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArticuloCodigoBarra', array($articuloCodigoBarra));

        return parent::setArticuloCodigoBarra($articuloCodigoBarra);
    }

    /**
     * {@inheritDoc}
     */
    public function getArticuloCodigoBarra()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArticuloCodigoBarra', array());

        return parent::getArticuloCodigoBarra();
    }

    /**
     * {@inheritDoc}
     */
    public function setArticuloPresentacion($articuloPresentacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArticuloPresentacion', array($articuloPresentacion));

        return parent::setArticuloPresentacion($articuloPresentacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getArticuloPresentacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArticuloPresentacion', array());

        return parent::getArticuloPresentacion();
    }

}
