<?php

namespace Proxies\__CG__\LineasTelefonicas\Policia\ERBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Usuarios extends \LineasTelefonicas\Policia\ERBundle\Entity\Usuarios implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'usuarioId', 'usuarioUsername', 'usuarioNombre', 'usuarioApellido', 'usuarioPass', 'usuarioMail', 'usuarioRol');
        }

        return array('__isInitialized__', 'usuarioId', 'usuarioUsername', 'usuarioNombre', 'usuarioApellido', 'usuarioPass', 'usuarioMail', 'usuarioRol');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Usuarios $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getUsuarioId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getUsuarioId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuarioId', array());

        return parent::getUsuarioId();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsuarioUsername($usuarioUsername)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsuarioUsername', array($usuarioUsername));

        return parent::setUsuarioUsername($usuarioUsername);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuarioUsername()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuarioUsername', array());

        return parent::getUsuarioUsername();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsuarioNombre($usuarioNombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsuarioNombre', array($usuarioNombre));

        return parent::setUsuarioNombre($usuarioNombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuarioNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuarioNombre', array());

        return parent::getUsuarioNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsuarioApellido($usuarioApellido)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsuarioApellido', array($usuarioApellido));

        return parent::setUsuarioApellido($usuarioApellido);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuarioApellido()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuarioApellido', array());

        return parent::getUsuarioApellido();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsuarioPass($usuarioPass)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsuarioPass', array($usuarioPass));

        return parent::setUsuarioPass($usuarioPass);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuarioPass()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuarioPass', array());

        return parent::getUsuarioPass();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsuarioMail($usuarioMail)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsuarioMail', array($usuarioMail));

        return parent::setUsuarioMail($usuarioMail);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuarioMail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuarioMail', array());

        return parent::getUsuarioMail();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsuarioRol($usuarioRol)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsuarioRol', array($usuarioRol));

        return parent::setUsuarioRol($usuarioRol);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuarioRol()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuarioRol', array());

        return parent::getUsuarioRol();
    }

}
