<?php

namespace Proxies\__CG__\LineasTelefonicas\Policia\ERBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Lineas extends \LineasTelefonicas\Policia\ERBundle\Entity\Lineas implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'lineaId', 'lineaNumero', 'lineaEmpresa', 'lineaPlan', 'lineaDestino', 'lineaCargo', 'lineaIMEI', 'lineaMarca', 'lineaModelo', 'lineaUltimoCambio', 'lineaVoz', 'lineaSms', 'lineaGprs', 'lineaDatos', 'lineaBlackberry', 'lineaRoaming', 'lineaObservaciones');
        }

        return array('__isInitialized__', 'lineaId', 'lineaNumero', 'lineaEmpresa', 'lineaPlan', 'lineaDestino', 'lineaCargo', 'lineaIMEI', 'lineaMarca', 'lineaModelo', 'lineaUltimoCambio', 'lineaVoz', 'lineaSms', 'lineaGprs', 'lineaDatos', 'lineaBlackberry', 'lineaRoaming', 'lineaObservaciones');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Lineas $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getLineaId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getLineaId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLineaId', array());

        return parent::getLineaId();
    }

    /**
     * {@inheritDoc}
     */
    public function setLineaNumero($lineaNumero)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLineaNumero', array($lineaNumero));

        return parent::setLineaNumero($lineaNumero);
    }

    /**
     * {@inheritDoc}
     */
    public function getLineaNumero()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLineaNumero', array());

        return parent::getLineaNumero();
    }

    /**
     * {@inheritDoc}
     */
    public function setLineaEmpresa($lineaEmpresa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLineaEmpresa', array($lineaEmpresa));

        return parent::setLineaEmpresa($lineaEmpresa);
    }

    /**
     * {@inheritDoc}
     */
    public function getLineaEmpresa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLineaEmpresa', array());

        return parent::getLineaEmpresa();
    }

    /**
     * {@inheritDoc}
     */
    public function setLineaPlan($lineaPlan)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLineaPlan', array($lineaPlan));

        return parent::setLineaPlan($lineaPlan);
    }

    /**
     * {@inheritDoc}
     */
    public function getLineaPlan()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLineaPlan', array());

        return parent::getLineaPlan();
    }

    /**
     * {@inheritDoc}
     */
    public function setLineaDestino($lineaDestino)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLineaDestino', array($lineaDestino));

        return parent::setLineaDestino($lineaDestino);
    }

    /**
     * {@inheritDoc}
     */
    public function getLineaDestino()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLineaDestino', array());

        return parent::getLineaDestino();
    }

    /**
     * {@inheritDoc}
     */
    public function setLineaCargo($lineaCargo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLineaCargo', array($lineaCargo));

        return parent::setLineaCargo($lineaCargo);
    }

    /**
     * {@inheritDoc}
     */
    public function getLineaCargo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLineaCargo', array());

        return parent::getLineaCargo();
    }

    /**
     * {@inheritDoc}
     */
    public function setLineaIMEI($lineaIMEI)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLineaIMEI', array($lineaIMEI));

        return parent::setLineaIMEI($lineaIMEI);
    }

    /**
     * {@inheritDoc}
     */
    public function getLineaIMEI()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLineaIMEI', array());

        return parent::getLineaIMEI();
    }

    /**
     * {@inheritDoc}
     */
    public function setLineaMarca($lineaMarca)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLineaMarca', array($lineaMarca));

        return parent::setLineaMarca($lineaMarca);
    }

    /**
     * {@inheritDoc}
     */
    public function getLineaMarca()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLineaMarca', array());

        return parent::getLineaMarca();
    }

    /**
     * {@inheritDoc}
     */
    public function setLineaModelo($lineaModelo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLineaModelo', array($lineaModelo));

        return parent::setLineaModelo($lineaModelo);
    }

    /**
     * {@inheritDoc}
     */
    public function getLineaModelo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLineaModelo', array());

        return parent::getLineaModelo();
    }

    /**
     * {@inheritDoc}
     */
    public function setLineaUltimoCambio($lineaUltimoCambio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLineaUltimoCambio', array($lineaUltimoCambio));

        return parent::setLineaUltimoCambio($lineaUltimoCambio);
    }

    /**
     * {@inheritDoc}
     */
    public function getLineaUltimoCambio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLineaUltimoCambio', array());

        return parent::getLineaUltimoCambio();
    }

    /**
     * {@inheritDoc}
     */
    public function setLineaVoz($lineaVoz)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLineaVoz', array($lineaVoz));

        return parent::setLineaVoz($lineaVoz);
    }

    /**
     * {@inheritDoc}
     */
    public function getLineaVoz()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLineaVoz', array());

        return parent::getLineaVoz();
    }

    /**
     * {@inheritDoc}
     */
    public function setLineaSms($lineaSms)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLineaSms', array($lineaSms));

        return parent::setLineaSms($lineaSms);
    }

    /**
     * {@inheritDoc}
     */
    public function getLineaSms()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLineaSms', array());

        return parent::getLineaSms();
    }

    /**
     * {@inheritDoc}
     */
    public function setLineaGprs($lineaGprs)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLineaGprs', array($lineaGprs));

        return parent::setLineaGprs($lineaGprs);
    }

    /**
     * {@inheritDoc}
     */
    public function getLineaGprs()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLineaGprs', array());

        return parent::getLineaGprs();
    }

    /**
     * {@inheritDoc}
     */
    public function setLineaDatos($lineaDatos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLineaDatos', array($lineaDatos));

        return parent::setLineaDatos($lineaDatos);
    }

    /**
     * {@inheritDoc}
     */
    public function getLineaDatos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLineaDatos', array());

        return parent::getLineaDatos();
    }

    /**
     * {@inheritDoc}
     */
    public function setLineaBlackberry($lineaBlackberry)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLineaBlackberry', array($lineaBlackberry));

        return parent::setLineaBlackberry($lineaBlackberry);
    }

    /**
     * {@inheritDoc}
     */
    public function getLineaBlackberry()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLineaBlackberry', array());

        return parent::getLineaBlackberry();
    }

    /**
     * {@inheritDoc}
     */
    public function setLineaRoaming($lineaRoaming)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLineaRoaming', array($lineaRoaming));

        return parent::setLineaRoaming($lineaRoaming);
    }

    /**
     * {@inheritDoc}
     */
    public function getLineaRoaming()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLineaRoaming', array());

        return parent::getLineaRoaming();
    }

    /**
     * {@inheritDoc}
     */
    public function setLineaObservaciones($lineaObservaciones)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLineaObservaciones', array($lineaObservaciones));

        return parent::setLineaObservaciones($lineaObservaciones);
    }

    /**
     * {@inheritDoc}
     */
    public function getLineaObservaciones()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLineaObservaciones', array());

        return parent::getLineaObservaciones();
    }

}
