parameters:
#    lineas_telefonicas_policia_er.example.class: LineasTelefonicas\Policia\ERBundle\Example

services:
#    lineas_telefonicas_policia_er.example:
#        class: %lineas_telefonicas_policia_er.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
