<?php

namespace Proxies\__CG__\Materiaweb\MateriaBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Company extends \Materiaweb\MateriaBundle\Entity\Company implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'companyId', 'companyClave', 'companyRazonSocial', 'companyNombreFantasia', 'companyMail', 'companyCalle', 'companyCalleNro', 'companyCp', 'companyLocalidad', 'companyProvincia', 'companyPais', 'companyCuit', 'companyPerFiscal', 'companyNiibb', 'companyCondiibb', 'companyActividad', 'companyObservaciones', 'companyNombreTitular', 'companyApellidoTitular', 'companyUsuarioTitular', 'companyPasswordTitular', 'companyActive');
        }

        return array('__isInitialized__', 'companyId', 'companyClave', 'companyRazonSocial', 'companyNombreFantasia', 'companyMail', 'companyCalle', 'companyCalleNro', 'companyCp', 'companyLocalidad', 'companyProvincia', 'companyPais', 'companyCuit', 'companyPerFiscal', 'companyNiibb', 'companyCondiibb', 'companyActividad', 'companyObservaciones', 'companyNombreTitular', 'companyApellidoTitular', 'companyUsuarioTitular', 'companyPasswordTitular', 'companyActive');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Company $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getCompanyId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getCompanyId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompanyId', array());

        return parent::getCompanyId();
    }

    /**
     * {@inheritDoc}
     */
    public function setCompanyClave($companyClave)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompanyClave', array($companyClave));

        return parent::setCompanyClave($companyClave);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompanyClave()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompanyClave', array());

        return parent::getCompanyClave();
    }

    /**
     * {@inheritDoc}
     */
    public function setCompanyRazonSocial($companyRazonSocial)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompanyRazonSocial', array($companyRazonSocial));

        return parent::setCompanyRazonSocial($companyRazonSocial);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompanyRazonSocial()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompanyRazonSocial', array());

        return parent::getCompanyRazonSocial();
    }

    /**
     * {@inheritDoc}
     */
    public function setCompanyNombreFantasia($companyNombreFantasia)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompanyNombreFantasia', array($companyNombreFantasia));

        return parent::setCompanyNombreFantasia($companyNombreFantasia);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompanyNombreFantasia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompanyNombreFantasia', array());

        return parent::getCompanyNombreFantasia();
    }

    /**
     * {@inheritDoc}
     */
    public function setCompanyMail($companyMail)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompanyMail', array($companyMail));

        return parent::setCompanyMail($companyMail);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompanyMail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompanyMail', array());

        return parent::getCompanyMail();
    }

    /**
     * {@inheritDoc}
     */
    public function setCompanyCalle($companyCalle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompanyCalle', array($companyCalle));

        return parent::setCompanyCalle($companyCalle);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompanyCalle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompanyCalle', array());

        return parent::getCompanyCalle();
    }

    /**
     * {@inheritDoc}
     */
    public function setCompanyCalleNro($companyCalleNro)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompanyCalleNro', array($companyCalleNro));

        return parent::setCompanyCalleNro($companyCalleNro);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompanyCalleNro()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompanyCalleNro', array());

        return parent::getCompanyCalleNro();
    }

    /**
     * {@inheritDoc}
     */
    public function setCompanyCp($companyCp)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompanyCp', array($companyCp));

        return parent::setCompanyCp($companyCp);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompanyCp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompanyCp', array());

        return parent::getCompanyCp();
    }

    /**
     * {@inheritDoc}
     */
    public function setCompanyLocalidad($companyLocalidad)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompanyLocalidad', array($companyLocalidad));

        return parent::setCompanyLocalidad($companyLocalidad);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompanyLocalidad()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompanyLocalidad', array());

        return parent::getCompanyLocalidad();
    }

    /**
     * {@inheritDoc}
     */
    public function setCompanyProvincia($companyProvincia)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompanyProvincia', array($companyProvincia));

        return parent::setCompanyProvincia($companyProvincia);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompanyProvincia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompanyProvincia', array());

        return parent::getCompanyProvincia();
    }

    /**
     * {@inheritDoc}
     */
    public function setCompanyPais($companyPais)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompanyPais', array($companyPais));

        return parent::setCompanyPais($companyPais);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompanyPais()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompanyPais', array());

        return parent::getCompanyPais();
    }

    /**
     * {@inheritDoc}
     */
    public function setCompanyCuit($companyCuit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompanyCuit', array($companyCuit));

        return parent::setCompanyCuit($companyCuit);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompanyCuit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompanyCuit', array());

        return parent::getCompanyCuit();
    }

    /**
     * {@inheritDoc}
     */
    public function setCompanyPerFiscal($companyPerFiscal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompanyPerFiscal', array($companyPerFiscal));

        return parent::setCompanyPerFiscal($companyPerFiscal);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompanyPerFiscal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompanyPerFiscal', array());

        return parent::getCompanyPerFiscal();
    }

    /**
     * {@inheritDoc}
     */
    public function setCompanyNiibb($companyNiibb)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompanyNiibb', array($companyNiibb));

        return parent::setCompanyNiibb($companyNiibb);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompanyNiibb()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompanyNiibb', array());

        return parent::getCompanyNiibb();
    }

    /**
     * {@inheritDoc}
     */
    public function setCompanyCondiibb($companyCondiibb)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompanyCondiibb', array($companyCondiibb));

        return parent::setCompanyCondiibb($companyCondiibb);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompanyCondiibb()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompanyCondiibb', array());

        return parent::getCompanyCondiibb();
    }

    /**
     * {@inheritDoc}
     */
    public function setCompanyActividad($companyActividad)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompanyActividad', array($companyActividad));

        return parent::setCompanyActividad($companyActividad);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompanyActividad()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompanyActividad', array());

        return parent::getCompanyActividad();
    }

    /**
     * {@inheritDoc}
     */
    public function setCompanyObservaciones($companyObservaciones)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompanyObservaciones', array($companyObservaciones));

        return parent::setCompanyObservaciones($companyObservaciones);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompanyObservaciones()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompanyObservaciones', array());

        return parent::getCompanyObservaciones();
    }

    /**
     * {@inheritDoc}
     */
    public function setCompanyNombreTitular($companyNombreTitular)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompanyNombreTitular', array($companyNombreTitular));

        return parent::setCompanyNombreTitular($companyNombreTitular);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompanyNombreTitular()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompanyNombreTitular', array());

        return parent::getCompanyNombreTitular();
    }

    /**
     * {@inheritDoc}
     */
    public function setCompanyApellidoTitular($companyApellidoTitular)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompanyApellidoTitular', array($companyApellidoTitular));

        return parent::setCompanyApellidoTitular($companyApellidoTitular);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompanyApellidoTitular()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompanyApellidoTitular', array());

        return parent::getCompanyApellidoTitular();
    }

    /**
     * {@inheritDoc}
     */
    public function setCompanyUsuarioTitular($companyUsuarioTitular)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompanyUsuarioTitular', array($companyUsuarioTitular));

        return parent::setCompanyUsuarioTitular($companyUsuarioTitular);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompanyUsuarioTitular()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompanyUsuarioTitular', array());

        return parent::getCompanyUsuarioTitular();
    }

    /**
     * {@inheritDoc}
     */
    public function setCompanyPasswordTitular($companyPasswordTitular)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompanyPasswordTitular', array($companyPasswordTitular));

        return parent::setCompanyPasswordTitular($companyPasswordTitular);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompanyPasswordTitular()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompanyPasswordTitular', array());

        return parent::getCompanyPasswordTitular();
    }

    /**
     * {@inheritDoc}
     */
    public function setCompanyActive($companyActive)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompanyActive', array($companyActive));

        return parent::setCompanyActive($companyActive);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompanyActive()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompanyActive', array());

        return parent::getCompanyActive();
    }

}
