parameters:
#    materia_web_materiaweb.example.class: Materia\Web\MateriawebBundle\Example

services:
#    materia_web_materiaweb.example:
#        class: %materia_web_materiaweb.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
