<?php

namespace Proxies\__CG__\LineasTelefonicas\Policia\ERBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Historico extends \LineasTelefonicas\Policia\ERBundle\Entity\Historico implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'historicoLineaId', 'historicoLineaCodArea', 'historicoLineaNumero', 'historicoLineaUsuarioClienteId', 'historicoLineaPlanId', 'historicoLineaVencimientoFactura', 'historicoLineaVencimientoPlan', 'historicoLineaAltaDeLinea', 'historicoLineaUsuarioModificacion', 'Historico');
        }

        return array('__isInitialized__', 'historicoLineaId', 'historicoLineaCodArea', 'historicoLineaNumero', 'historicoLineaUsuarioClienteId', 'historicoLineaPlanId', 'historicoLineaVencimientoFactura', 'historicoLineaVencimientoPlan', 'historicoLineaAltaDeLinea', 'historicoLineaUsuarioModificacion', 'Historico');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Historico $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getHistorico()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHistorico', array());

        return parent::getHistorico();
    }

    /**
     * {@inheritDoc}
     */
    public function setHistoricoLineaId($historicoLineaId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHistoricoLineaId', array($historicoLineaId));

        return parent::setHistoricoLineaId($historicoLineaId);
    }

    /**
     * {@inheritDoc}
     */
    public function getHistoricoLineaId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHistoricoLineaId', array());

        return parent::getHistoricoLineaId();
    }

    /**
     * {@inheritDoc}
     */
    public function setHistoricoLineaCodArea($historicoLineaCodArea)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHistoricoLineaCodArea', array($historicoLineaCodArea));

        return parent::setHistoricoLineaCodArea($historicoLineaCodArea);
    }

    /**
     * {@inheritDoc}
     */
    public function getHistoricoLineaCodArea()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHistoricoLineaCodArea', array());

        return parent::getHistoricoLineaCodArea();
    }

    /**
     * {@inheritDoc}
     */
    public function setHistoricoLineaNumero($historicoLineaNumero)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHistoricoLineaNumero', array($historicoLineaNumero));

        return parent::setHistoricoLineaNumero($historicoLineaNumero);
    }

    /**
     * {@inheritDoc}
     */
    public function getHistoricoLineaNumero()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHistoricoLineaNumero', array());

        return parent::getHistoricoLineaNumero();
    }

    /**
     * {@inheritDoc}
     */
    public function setHistoricoLineaUsuarioClienteId($historicoLineaUsuarioClienteId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHistoricoLineaUsuarioClienteId', array($historicoLineaUsuarioClienteId));

        return parent::setHistoricoLineaUsuarioClienteId($historicoLineaUsuarioClienteId);
    }

    /**
     * {@inheritDoc}
     */
    public function getHistoricoLineaUsuarioClienteId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHistoricoLineaUsuarioClienteId', array());

        return parent::getHistoricoLineaUsuarioClienteId();
    }

    /**
     * {@inheritDoc}
     */
    public function setHistoricoLineaPlanId($historicoLineaPlanId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHistoricoLineaPlanId', array($historicoLineaPlanId));

        return parent::setHistoricoLineaPlanId($historicoLineaPlanId);
    }

    /**
     * {@inheritDoc}
     */
    public function getHistoricoLineaPlanId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHistoricoLineaPlanId', array());

        return parent::getHistoricoLineaPlanId();
    }

    /**
     * {@inheritDoc}
     */
    public function setHistoricoLineaVencimientoFactura($historicoLineaVencimientoFactura)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHistoricoLineaVencimientoFactura', array($historicoLineaVencimientoFactura));

        return parent::setHistoricoLineaVencimientoFactura($historicoLineaVencimientoFactura);
    }

    /**
     * {@inheritDoc}
     */
    public function getHistoricoLineaVencimientoFactura()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHistoricoLineaVencimientoFactura', array());

        return parent::getHistoricoLineaVencimientoFactura();
    }

    /**
     * {@inheritDoc}
     */
    public function setHistoricoLineaVencimientoPlan($historicoLineaVencimientoPlan)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHistoricoLineaVencimientoPlan', array($historicoLineaVencimientoPlan));

        return parent::setHistoricoLineaVencimientoPlan($historicoLineaVencimientoPlan);
    }

    /**
     * {@inheritDoc}
     */
    public function getHistoricoLineaVencimientoPlan()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHistoricoLineaVencimientoPlan', array());

        return parent::getHistoricoLineaVencimientoPlan();
    }

    /**
     * {@inheritDoc}
     */
    public function setHistoricoLineaAltaDeLinea($historicoLineaAltaDeLinea)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHistoricoLineaAltaDeLinea', array($historicoLineaAltaDeLinea));

        return parent::setHistoricoLineaAltaDeLinea($historicoLineaAltaDeLinea);
    }

    /**
     * {@inheritDoc}
     */
    public function getHistoricoLineaAltaDeLinea()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHistoricoLineaAltaDeLinea', array());

        return parent::getHistoricoLineaAltaDeLinea();
    }

    /**
     * {@inheritDoc}
     */
    public function setHistoricoLineaUsuarioModificacion($historicoLineaUsuarioModificacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHistoricoLineaUsuarioModificacion', array($historicoLineaUsuarioModificacion));

        return parent::setHistoricoLineaUsuarioModificacion($historicoLineaUsuarioModificacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getHistoricoLineaUsuarioModificacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHistoricoLineaUsuarioModificacion', array());

        return parent::getHistoricoLineaUsuarioModificacion();
    }

}
