<?php

namespace Proxies\__CG__\LineasTelefonicas\Policia\ERBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Planes extends \LineasTelefonicas\Policia\ERBundle\Entity\Planes implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'planId', 'planEmpresa', 'planNombre', 'planMonto', 'planInternet', 'planSMS', 'planMinutos', 'planCredito');
        }

        return array('__isInitialized__', 'planId', 'planEmpresa', 'planNombre', 'planMonto', 'planInternet', 'planSMS', 'planMinutos', 'planCredito');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Planes $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getPlanId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getPlanId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPlanId', array());

        return parent::getPlanId();
    }

    /**
     * {@inheritDoc}
     */
    public function setPlanEmpresa($planEmpresa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPlanEmpresa', array($planEmpresa));

        return parent::setPlanEmpresa($planEmpresa);
    }

    /**
     * {@inheritDoc}
     */
    public function getPlanEmpresa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPlanEmpresa', array());

        return parent::getPlanEmpresa();
    }

    /**
     * {@inheritDoc}
     */
    public function setPlanNombre($planNombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPlanNombre', array($planNombre));

        return parent::setPlanNombre($planNombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getPlanNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPlanNombre', array());

        return parent::getPlanNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setPlanMonto($planMonto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPlanMonto', array($planMonto));

        return parent::setPlanMonto($planMonto);
    }

    /**
     * {@inheritDoc}
     */
    public function getPlanMonto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPlanMonto', array());

        return parent::getPlanMonto();
    }

    /**
     * {@inheritDoc}
     */
    public function setPlanInternet($planInternet)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPlanInternet', array($planInternet));

        return parent::setPlanInternet($planInternet);
    }

    /**
     * {@inheritDoc}
     */
    public function getPlanInternet()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPlanInternet', array());

        return parent::getPlanInternet();
    }

    /**
     * {@inheritDoc}
     */
    public function setPlanSMS($planSMS)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPlanSMS', array($planSMS));

        return parent::setPlanSMS($planSMS);
    }

    /**
     * {@inheritDoc}
     */
    public function getPlanSMS()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPlanSMS', array());

        return parent::getPlanSMS();
    }

    /**
     * {@inheritDoc}
     */
    public function setPlanMinutos($planMinutos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPlanMinutos', array($planMinutos));

        return parent::setPlanMinutos($planMinutos);
    }

    /**
     * {@inheritDoc}
     */
    public function getPlanMinutos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPlanMinutos', array());

        return parent::getPlanMinutos();
    }

    /**
     * {@inheritDoc}
     */
    public function setPlanCredito($planCredito)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPlanCredito', array($planCredito));

        return parent::setPlanCredito($planCredito);
    }

    /**
     * {@inheritDoc}
     */
    public function getPlanCredito()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPlanCredito', array());

        return parent::getPlanCredito();
    }

}
