<?php

namespace Proxies\__CG__\Materiaweb\MateriaBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ArticulosMarcacion extends \Materiaweb\MateriaBundle\Entity\ArticulosMarcacion implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'ArtDescIdTabla', 'ArtDescIdCompany', 'ArtDescCodart', 'ArtDescNroOrden', 'ArtDescDetalle', 'ArtDescValor', 'ArtMarcIdTabla', 'ArtMarcCodart', 'ArtMarcNroOrden', 'ArtMarcDetalle', 'ArtMarcPrecioNetoOrigen1', 'ArtMarcAdicAntesCalc', 'ArtMarcPrecioNetoOrigen2', 'ArtMarcValor', 'ArtMarcPrecioNetoCalculado', 'ArtMarcAlicutaImp1', 'ArtMarcValorImp1', 'ArtMarcAlicutaImp2', 'ArtMarcValorImp2', 'ArtMarcAlicutaImp3', 'ArtMarcValorImp3', 'ArtMarcPrecioFinalCalculado', 'ArtMarcAdicDpsCalculo', 'ArtMarcPrecioFinal');
        }

        return array('__isInitialized__', 'ArtDescIdTabla', 'ArtDescIdCompany', 'ArtDescCodart', 'ArtDescNroOrden', 'ArtDescDetalle', 'ArtDescValor', 'ArtMarcIdTabla', 'ArtMarcCodart', 'ArtMarcNroOrden', 'ArtMarcDetalle', 'ArtMarcPrecioNetoOrigen1', 'ArtMarcAdicAntesCalc', 'ArtMarcPrecioNetoOrigen2', 'ArtMarcValor', 'ArtMarcPrecioNetoCalculado', 'ArtMarcAlicutaImp1', 'ArtMarcValorImp1', 'ArtMarcAlicutaImp2', 'ArtMarcValorImp2', 'ArtMarcAlicutaImp3', 'ArtMarcValorImp3', 'ArtMarcPrecioFinalCalculado', 'ArtMarcAdicDpsCalculo', 'ArtMarcPrecioFinal');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (ArticulosMarcacion $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getArtMarcIdTabla()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArtMarcIdTabla', array());

        return parent::getArtMarcIdTabla();
    }

    /**
     * {@inheritDoc}
     */
    public function setArtMarcCodart($artMarcCodart)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArtMarcCodart', array($artMarcCodart));

        return parent::setArtMarcCodart($artMarcCodart);
    }

    /**
     * {@inheritDoc}
     */
    public function getArtMarcCodart()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArtMarcCodart', array());

        return parent::getArtMarcCodart();
    }

    /**
     * {@inheritDoc}
     */
    public function setArtMarcNroOrden($artMarcNroOrden)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArtMarcNroOrden', array($artMarcNroOrden));

        return parent::setArtMarcNroOrden($artMarcNroOrden);
    }

    /**
     * {@inheritDoc}
     */
    public function getArtMarcNroOrden()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArtMarcNroOrden', array());

        return parent::getArtMarcNroOrden();
    }

    /**
     * {@inheritDoc}
     */
    public function setArtMarcDetalle($artMarcDetalle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArtMarcDetalle', array($artMarcDetalle));

        return parent::setArtMarcDetalle($artMarcDetalle);
    }

    /**
     * {@inheritDoc}
     */
    public function getArtMarcDetalle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArtMarcDetalle', array());

        return parent::getArtMarcDetalle();
    }

    /**
     * {@inheritDoc}
     */
    public function setArtMarcPrecioNetoOrigen1($artMarcPrecioNetoOrigen1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArtMarcPrecioNetoOrigen1', array($artMarcPrecioNetoOrigen1));

        return parent::setArtMarcPrecioNetoOrigen1($artMarcPrecioNetoOrigen1);
    }

    /**
     * {@inheritDoc}
     */
    public function getArtMarcPrecioNetoOrigen1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArtMarcPrecioNetoOrigen1', array());

        return parent::getArtMarcPrecioNetoOrigen1();
    }

    /**
     * {@inheritDoc}
     */
    public function setArtMarcAdicAntesCalc($artMarcAdicAntesCalc)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArtMarcAdicAntesCalc', array($artMarcAdicAntesCalc));

        return parent::setArtMarcAdicAntesCalc($artMarcAdicAntesCalc);
    }

    /**
     * {@inheritDoc}
     */
    public function getArtMarcAdicAntesCalc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArtMarcAdicAntesCalc', array());

        return parent::getArtMarcAdicAntesCalc();
    }

    /**
     * {@inheritDoc}
     */
    public function setArtMarcPrecioNetoOrigen2($artMarcPrecioNetoOrigen2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArtMarcPrecioNetoOrigen2', array($artMarcPrecioNetoOrigen2));

        return parent::setArtMarcPrecioNetoOrigen2($artMarcPrecioNetoOrigen2);
    }

    /**
     * {@inheritDoc}
     */
    public function getArtMarcPrecioNetoOrigen2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArtMarcPrecioNetoOrigen2', array());

        return parent::getArtMarcPrecioNetoOrigen2();
    }

    /**
     * {@inheritDoc}
     */
    public function setArtMarcValor($artMarcValor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArtMarcValor', array($artMarcValor));

        return parent::setArtMarcValor($artMarcValor);
    }

    /**
     * {@inheritDoc}
     */
    public function getArtMarcValor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArtMarcValor', array());

        return parent::getArtMarcValor();
    }

    /**
     * {@inheritDoc}
     */
    public function setArtMarcPrecioNetoCalculado($artMarcPrecioNetoCalculado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArtMarcPrecioNetoCalculado', array($artMarcPrecioNetoCalculado));

        return parent::setArtMarcPrecioNetoCalculado($artMarcPrecioNetoCalculado);
    }

    /**
     * {@inheritDoc}
     */
    public function getArtMarcPrecioNetoCalculado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArtMarcPrecioNetoCalculado', array());

        return parent::getArtMarcPrecioNetoCalculado();
    }

    /**
     * {@inheritDoc}
     */
    public function setArtMarcAlicutaImp1($artMarcAlicutaImp1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArtMarcAlicutaImp1', array($artMarcAlicutaImp1));

        return parent::setArtMarcAlicutaImp1($artMarcAlicutaImp1);
    }

    /**
     * {@inheritDoc}
     */
    public function getArtMarcAlicutaImp1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArtMarcAlicutaImp1', array());

        return parent::getArtMarcAlicutaImp1();
    }

    /**
     * {@inheritDoc}
     */
    public function setArtMarcValorImp1($artMarcValorImp1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArtMarcValorImp1', array($artMarcValorImp1));

        return parent::setArtMarcValorImp1($artMarcValorImp1);
    }

    /**
     * {@inheritDoc}
     */
    public function getArtMarcValorImp1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArtMarcValorImp1', array());

        return parent::getArtMarcValorImp1();
    }

    /**
     * {@inheritDoc}
     */
    public function setArtMarcAlicutaImp2($artMarcAlicutaImp2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArtMarcAlicutaImp2', array($artMarcAlicutaImp2));

        return parent::setArtMarcAlicutaImp2($artMarcAlicutaImp2);
    }

    /**
     * {@inheritDoc}
     */
    public function getArtMarcAlicutaImp2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArtMarcAlicutaImp2', array());

        return parent::getArtMarcAlicutaImp2();
    }

    /**
     * {@inheritDoc}
     */
    public function setArtMarcValorImp2($artMarcValorImp2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArtMarcValorImp2', array($artMarcValorImp2));

        return parent::setArtMarcValorImp2($artMarcValorImp2);
    }

    /**
     * {@inheritDoc}
     */
    public function getArtMarcValorImp2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArtMarcValorImp2', array());

        return parent::getArtMarcValorImp2();
    }

    /**
     * {@inheritDoc}
     */
    public function setArtMarcAlicutaImp3($artMarcAlicutaImp3)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArtMarcAlicutaImp3', array($artMarcAlicutaImp3));

        return parent::setArtMarcAlicutaImp3($artMarcAlicutaImp3);
    }

    /**
     * {@inheritDoc}
     */
    public function getArtMarcAlicutaImp3()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArtMarcAlicutaImp3', array());

        return parent::getArtMarcAlicutaImp3();
    }

    /**
     * {@inheritDoc}
     */
    public function setArtMarcValorImp3($artMarcValorImp3)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArtMarcValorImp3', array($artMarcValorImp3));

        return parent::setArtMarcValorImp3($artMarcValorImp3);
    }

    /**
     * {@inheritDoc}
     */
    public function getArtMarcValorImp3()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArtMarcValorImp3', array());

        return parent::getArtMarcValorImp3();
    }

    /**
     * {@inheritDoc}
     */
    public function setArtMarcPrecioFinalCalculado($artMarcPrecioFinalCalculado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArtMarcPrecioFinalCalculado', array($artMarcPrecioFinalCalculado));

        return parent::setArtMarcPrecioFinalCalculado($artMarcPrecioFinalCalculado);
    }

    /**
     * {@inheritDoc}
     */
    public function getArtMarcPrecioFinalCalculado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArtMarcPrecioFinalCalculado', array());

        return parent::getArtMarcPrecioFinalCalculado();
    }

    /**
     * {@inheritDoc}
     */
    public function setArtMarcAdicDpsCalculo($artMarcAdicDpsCalculo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArtMarcAdicDpsCalculo', array($artMarcAdicDpsCalculo));

        return parent::setArtMarcAdicDpsCalculo($artMarcAdicDpsCalculo);
    }

    /**
     * {@inheritDoc}
     */
    public function getArtMarcAdicDpsCalculo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArtMarcAdicDpsCalculo', array());

        return parent::getArtMarcAdicDpsCalculo();
    }

    /**
     * {@inheritDoc}
     */
    public function setArtMarcPrecioFinal($artMarcPrecioFinal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArtMarcPrecioFinal', array($artMarcPrecioFinal));

        return parent::setArtMarcPrecioFinal($artMarcPrecioFinal);
    }

    /**
     * {@inheritDoc}
     */
    public function getArtMarcPrecioFinal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArtMarcPrecioFinal', array());

        return parent::getArtMarcPrecioFinal();
    }

}
