<?php
// src/LineasTelefonicas/Policia/ERBundle/DataFixtures/ORM/DestinoFixtures.php

namespace LineasTelefonicas\Policia\ERBundle\DataFixtures\ORM;

use Doctrine\Common\DataFixtures\FixtureInterface;
use Doctrine\Common\Persistence\ObjectManager;
use LineasTelefonicas\Policia\ERBundle\Entity\Destino;

class DestinoFixtures implements FixtureInterface
{
    public function load(ObjectManager $manager)
    {
        $destino1	 = new Destino();
		$destino2	 = new Destino();
		$destino3	 = new Destino();
		$destino4	 = new Destino();
		$destino5	 = new Destino();
		$destino6	 = new Destino();
		$destino7	 = new Destino();
		$destino8	 = new Destino();
		$destino9	 = new Destino();
		$destino10	 = new Destino();
		$destino11	 = new Destino();
		$destino12	 = new Destino();
		$destino13	 = new Destino();
		$destino14	 = new Destino();
		$destino15	 = new Destino();
		$destino16	 = new Destino();
		$destino17	 = new Destino();
		$destino18	 = new Destino();
		$destino19	 = new Destino();
		$destino20	 = new Destino();
		$destino21	 = new Destino();
		$destino22	 = new Destino();
		$destino23	 = new Destino();
		$destino24	 = new Destino();
		$destino25	 = new Destino();
		$destino26	 = new Destino();
		$destino27	 = new Destino();
		$destino28	 = new Destino();
		$destino29	 = new Destino();
		$destino30	 = new Destino();
		$destino31	 = new Destino();
		$destino32	 = new Destino();
		$destino33	 = new Destino();
		$destino34	 = new Destino();
		$destino35	 = new Destino();
		$destino36	 = new Destino();
		$destino37	 = new Destino();
		$destino38	 = new Destino();
		$destino39	 = new Destino();
		$destino40	 = new Destino();
		$destino41	 = new Destino();
		$destino42	 = new Destino();
		$destino43	 = new Destino();
		$destino44	 = new Destino();
		$destino45	 = new Destino();
		$destino46	 = new Destino();
		$destino47	 = new Destino();
		$destino48	 = new Destino();
		$destino49	 = new Destino();
		$destino50	 = new Destino();
		$destino51	 = new Destino();
		$destino52	 = new Destino();
		$destino53	 = new Destino();
		$destino54	 = new Destino();
		$destino55	 = new Destino();
		$destino56	 = new Destino();
		$destino57	 = new Destino();
		$destino58	 = new Destino();
		$destino59	 = new Destino();
		$destino60	 = new Destino();
		$destino61	 = new Destino();
		$destino62	 = new Destino();
		$destino63	 = new Destino();
		$destino64	 = new Destino();
		$destino65	 = new Destino();
		$destino66	 = new Destino();
		$destino67	 = new Destino();
		$destino68	 = new Destino();
		$destino69	 = new Destino();
		$destino70	 = new Destino();
		$destino71	 = new Destino();
		$destino72	 = new Destino();
		$destino73	 = new Destino();
		$destino74	 = new Destino();
		$destino75	 = new Destino();
		$destino76	 = new Destino();
		$destino77	 = new Destino();
		$destino78	 = new Destino();
		$destino79	 = new Destino();
		$destino80	 = new Destino();
		$destino81	 = new Destino();
		$destino82	 = new Destino();
		$destino83	 = new Destino();
		$destino84	 = new Destino();
		$destino85	 = new Destino();
		$destino86	 = new Destino();
		$destino87	 = new Destino();
		$destino88	 = new Destino();
		$destino89	 = new Destino();
		$destino90	 = new Destino();
		$destino91	 = new Destino();
		$destino92	 = new Destino();
		$destino93	 = new Destino();

		$destino1	 ->setDestinoNombre("Aldea Eigenfeld");
		$destino2	 ->setDestinoNombre("Aldea María Luisa");
		$destino3	 ->setDestinoNombre("Aldea San Antonio");
		$destino4	 ->setDestinoNombre("Aldea San Rafael");
		$destino5	 ->setDestinoNombre("Aldea Santa María");
		$destino6	 ->setDestinoNombre("Aldea Santa Rosa");
		$destino7	 ->setDestinoNombre("Antonio Tomás");
		$destino8	 ->setDestinoNombre("Antonio Tomás");
		$destino9	 ->setDestinoNombre("Arroyo Burgos");
		$destino10	 ->setDestinoNombre("Arroyo Corralito");
		$destino11	 ->setDestinoNombre("Arroyo Maturrango");
		$destino12	 ->setDestinoNombre("Arroyo Palo Seco");
		$destino13	 ->setDestinoNombre("Cerrito");
		$destino14	 ->setDestinoNombre("Colonia Avellaneda");
		$destino15	 ->setDestinoNombre("Colonia Celina");
		$destino16	 ->setDestinoNombre("Colonia Cerrito");
		$destino17	 ->setDestinoNombre("Colonia Crespo");
		$destino18	 ->setDestinoNombre("Colonia Merou");
		$destino19	 ->setDestinoNombre("Colonia Reffino");
		$destino20	 ->setDestinoNombre("Crespo");
		$destino21	 ->setDestinoNombre("Distrito Tala");
		$destino22	 ->setDestinoNombre("El Palenque");
		$destino23	 ->setDestinoNombre("El Pingo");
		$destino24	 ->setDestinoNombre("Espinillo");
		$destino25	 ->setDestinoNombre("Espinillo Norte");
		$destino26	 ->setDestinoNombre("Hasenkamp");
		$destino27	 ->setDestinoNombre("La Picada");
		$destino28	 ->setDestinoNombre("Las Tunas");
		$destino29	 ->setDestinoNombre("María Grande");
		$destino30	 ->setDestinoNombre("María Grande Primera");
		$destino31	 ->setDestinoNombre("María Grande Segunda");
		$destino32	 ->setDestinoNombre("María Grande Segunda");
		$destino33	 ->setDestinoNombre("Oro Verde");
		$destino34	 ->setDestinoNombre("Paraná");
		$destino35	 ->setDestinoNombre("Paraná");
		$destino36	 ->setDestinoNombre("Paso de la Arena");
		$destino37	 ->setDestinoNombre("Paso de la Piedra");
		$destino38	 ->setDestinoNombre("Pueblo Bellocq");
		$destino39	 ->setDestinoNombre("Pueblo Brugo");
		$destino40	 ->setDestinoNombre("Puerto Curtiembre");
		$destino41	 ->setDestinoNombre("Quebracho");
		$destino42	 ->setDestinoNombre("Quebracho");
		$destino43	 ->setDestinoNombre("San Benito");
		$destino44	 ->setDestinoNombre("Santa Luisa");
		$destino45	 ->setDestinoNombre("Sauce");
		$destino46	 ->setDestinoNombre("Sauce Montrull");
		$destino47	 ->setDestinoNombre("Sauce Pinto");
		$destino48	 ->setDestinoNombre("Seguí");
		$destino49	 ->setDestinoNombre("Sosa");
		$destino50	 ->setDestinoNombre("Tabossi");
		$destino51	 ->setDestinoNombre("Tala");
		$destino52	 ->setDestinoNombre("Tezanos Pinto");
		$destino53	 ->setDestinoNombre("Viale");
		$destino54	 ->setDestinoNombre("Villa Fontana");
		$destino55	 ->setDestinoNombre("Villa Gobernador Etchevehere");
		$destino56	 ->setDestinoNombre("Villa Hernandarias");
		$destino57	 ->setDestinoNombre("Villa Urquiza");
		$destino58	 ->setDestinoNombre("El Palenque");
		$destino59	 ->setDestinoNombre("El Pingo");
		$destino60	 ->setDestinoNombre("Espinillo");
		$destino61	 ->setDestinoNombre("Espinillo Norte");
		$destino62	 ->setDestinoNombre("Hasenkamp");
		$destino63	 ->setDestinoNombre("La Picada");
		$destino64	 ->setDestinoNombre("Las Tunas");
		$destino65	 ->setDestinoNombre("María Grande");
		$destino66	 ->setDestinoNombre("María Grande Primera");
		$destino67	 ->setDestinoNombre("María Grande Segunda");
		$destino68	 ->setDestinoNombre("María Grande Segunda");
		$destino69	 ->setDestinoNombre("Oro Verde");
		$destino70	 ->setDestinoNombre("Paraná");
		$destino71	 ->setDestinoNombre("Paraná");
		$destino72	 ->setDestinoNombre("Paso de la Arena");
		$destino73	 ->setDestinoNombre("Paso de la Piedra");
		$destino74	 ->setDestinoNombre("Pueblo Bellocq");
		$destino75	 ->setDestinoNombre("Pueblo Brugo");
		$destino76	 ->setDestinoNombre("Puerto Curtiembre");
		$destino77	 ->setDestinoNombre("Quebracho");
		$destino78	 ->setDestinoNombre("Quebracho");
		$destino79	 ->setDestinoNombre("San Benito");
		$destino80	 ->setDestinoNombre("Santa Luisa");
		$destino81	 ->setDestinoNombre("Sauce");
		$destino82	 ->setDestinoNombre("Sauce Montrull");
		$destino83	 ->setDestinoNombre("Sauce Pinto");
		$destino84	 ->setDestinoNombre("Seguí");
		$destino85	 ->setDestinoNombre("Sosa");
		$destino86	 ->setDestinoNombre("Tabossi");
		$destino87	 ->setDestinoNombre("Tala");
		$destino88	 ->setDestinoNombre("Tezanos Pinto");
		$destino89	 ->setDestinoNombre("Viale");
		$destino90	 ->setDestinoNombre("Villa Fontana");;
		$destino91	 ->setDestinoNombre("Villa Gobernador Etchevehere");
		$destino92	 ->setDestinoNombre("Villa Hernandarias");
		$destino93	 ->setDestinoNombre("Villa Urquiza");
		
		$manager->persist(	$destino1	);
		$manager->persist(	$destino2	);
		$manager->persist(	$destino3	);
		$manager->persist(	$destino4	);
		$manager->persist(	$destino5	);
		$manager->persist(	$destino6	);
		$manager->persist(	$destino7	);
		$manager->persist(	$destino8	);
		$manager->persist(	$destino9	);
		$manager->persist(	$destino10	);
		$manager->persist(	$destino11	);
		$manager->persist(	$destino12	);
		$manager->persist(	$destino13	);
		$manager->persist(	$destino14	);
		$manager->persist(	$destino15	);
		$manager->persist(	$destino16	);
		$manager->persist(	$destino17	);
		$manager->persist(	$destino18	);
		$manager->persist(	$destino19	);
		$manager->persist(	$destino20	);
		$manager->persist(	$destino21	);
		$manager->persist(	$destino22	);
		$manager->persist(	$destino23	);
		$manager->persist(	$destino24	);
		$manager->persist(	$destino25	);
		$manager->persist(	$destino26	);
		$manager->persist(	$destino27	);
		$manager->persist(	$destino28	);
		$manager->persist(	$destino29	);
		$manager->persist(	$destino30	);
		$manager->persist(	$destino31	);
		$manager->persist(	$destino32	);
		$manager->persist(	$destino33	);
		$manager->persist(	$destino34	);
		$manager->persist(	$destino35	);
		$manager->persist(	$destino36	);
		$manager->persist(	$destino37	);
		$manager->persist(	$destino38	);
		$manager->persist(	$destino39	);
		$manager->persist(	$destino40	);
		$manager->persist(	$destino41	);
		$manager->persist(	$destino42	);
		$manager->persist(	$destino43	);
		$manager->persist(	$destino44	);
		$manager->persist(	$destino45	);
		$manager->persist(	$destino46	);
		$manager->persist(	$destino47	);
		$manager->persist(	$destino48	);
		$manager->persist(	$destino49	);
		$manager->persist(	$destino50	);
		$manager->persist(	$destino51	);
		$manager->persist(	$destino52	);
		$manager->persist(	$destino53	);
		$manager->persist(	$destino54	);
		$manager->persist(	$destino55	);
		$manager->persist(	$destino56	);
		$manager->persist(	$destino57	);
		$manager->persist(	$destino58	);
		$manager->persist(	$destino59	);
		$manager->persist(	$destino60	);
		$manager->persist(	$destino61	);
		$manager->persist(	$destino62	);
		$manager->persist(	$destino63	);
		$manager->persist(	$destino64	);
		$manager->persist(	$destino65	);
		$manager->persist(	$destino66	);
		$manager->persist(	$destino67	);
		$manager->persist(	$destino68	);
		$manager->persist(	$destino69	);
		$manager->persist(	$destino70	);
		$manager->persist(	$destino71	);
		$manager->persist(	$destino72	);
		$manager->persist(	$destino73	);
		$manager->persist(	$destino74	);
		$manager->persist(	$destino75	);
		$manager->persist(	$destino76	);
		$manager->persist(	$destino77	);
		$manager->persist(	$destino78	);
		$manager->persist(	$destino79	);
		$manager->persist(	$destino80	);
		$manager->persist(	$destino81	);
		$manager->persist(	$destino82	);
		$manager->persist(	$destino83	);
		$manager->persist(	$destino84	);
		$manager->persist(	$destino85	);
		$manager->persist(	$destino86	);
		$manager->persist(	$destino87	);
		$manager->persist(	$destino88	);
		$manager->persist(	$destino89	);
		$manager->persist(	$destino90	);
		$manager->persist(	$destino91	);
		$manager->persist(	$destino92	);
		$manager->persist(	$destino93	);

		$manager->flush();
    }

}