parameters:
#    materia_sql.example.class: Materia\SqlBundle\Example

services:
#    materia_sql.example:
#        class: %materia_sql.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
